/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _VOICE_EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _VOICE_EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The voice_ei_impulse_handle_t should
 *  be passed to voice_ei_voice_run_classifier() function to use this specific impulse.
 *  This file should only be included in voice_ei_voice_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "voice-tflite-model/tflite_learn_964091_5_compiled.h"
#include "voice-edge-impulse-sdk/classifier/voice_ei_model_types.h"
#include "voice-edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "voice-edge-impulse-sdk/classifier/postprocessing/voice_ei_postprocessing_common.h"

const char* voice_ei_classifier_inferencing_categories_964091_1[] = { "Turn_Off", "Turn_On", "Unknown" };

voice_ei_dsp_named_axis_t voice_ei_dsp_config_964091_4_named_axes[] = {
    { .name = "Signal", .axis = 0 }
};
size_t voice_ei_dsp_config_964091_4_named_axes_size = 1;
VOICE_EI_CLASSIFIER_DSP_AXES_INDEX_TYPE voice_ei_dsp_config_964091_4_axes[] = { 0 };
const uint32_t voice_ei_dsp_config_964091_4_axes_size = 1;
voice_ei_dsp_config_mfcc_t voice_ei_dsp_config_964091_4 = {
    4, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    voice_ei_dsp_config_964091_4_named_axes, // named axes
    voice_ei_dsp_config_964091_4_named_axes_size, // size of the named axes array
    13, // int num_cepstral
    0.02f, // float frame_length
    0.02f, // float frame_stride
    32, // int num_filters
    256, // int fft_length
    101, // int win_size
    0, // int low_frequency
    0, // int high_frequency
    0.98f, // float pre_cof
    1 // int pre_shift
};

const uint8_t voice_ei_dsp_blocks_964091_1_size = 1;
voice_ei_model_dsp_t voice_ei_dsp_blocks_964091_1[voice_ei_dsp_blocks_964091_1_size] = {
    { // DSP block 4
        4,
        650, // output size
        &extract_mfcc_features, // DSP function pointer
        (void*)&voice_ei_dsp_config_964091_4, // pointer to config struct
        voice_ei_dsp_config_964091_4_axes, // array of offsets into the input stream, one for each axis
        voice_ei_dsp_config_964091_4_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const voice_ei_config_tflite_eon_graph_t voice_ei_config_graph_964091_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_964091_5_init,
    .model_invoke = &tflite_learn_964091_5_invoke,
    .model_reset = &tflite_learn_964091_5_reset,
    .model_input = &tflite_learn_964091_5_input,
    .model_output = &tflite_learn_964091_5_output,
};

const uint8_t voice_ei_output_tensors_indices_964091_5[1] = { 0 };
const uint8_t voice_ei_output_tensors_size_964091_5 = 1;
voice_ei_learning_block_config_tflite_graph_t voice_ei_learning_block_config_964091_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = voice_ei_output_tensors_indices_964091_5,
    .output_tensors_size = voice_ei_output_tensors_size_964091_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&voice_ei_config_graph_964091_5,
    .dequantize_output = 0,
};

const uint8_t voice_ei_learning_blocks_964091_1_size = 1;
const uint32_t voice_ei_learning_block_964091_5_inputs[1] = { 4 };
const uint8_t voice_ei_learning_block_964091_5_inputs_size = 1;
const voice_ei_learning_block_t voice_ei_learning_blocks_964091_1[voice_ei_learning_blocks_964091_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&voice_ei_learning_block_config_964091_5,
        VOICE_EI_CLASSIFIER_IMAGE_SCALING_NONE,
        voice_ei_learning_block_964091_5_inputs,
        voice_ei_learning_block_964091_5_inputs_size,
    },
};

voice_ei_fill_result_classification_i8_config_t voice_ei_fill_result_classification_i8_config_964091_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t voice_ei_postprocessing_blocks_964091_1_size = 1;
const voice_ei_postprocessing_block_t voice_ei_postprocessing_blocks_964091_1[voice_ei_postprocessing_blocks_964091_1_size] = {
    {
        .block_id = 5,
        .type = VOICE_EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&voice_ei_fill_result_classification_i8_config_964091_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_964091_1_size = 0;

uint32_t *freeform_outputs_964091_1 = nullptr;

const voice_ei_impulse_t impulse_964091_1 = {
    .project_id = 964091,
    .project_owner = "TanLe",
    .project_name = "VoiceCommand_ESP32-S3",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 4,

    .nn_input_frame_size = 650,
    .raw_sample_count = 16000,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 16000 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 0.0625,
    .frequency = 16000,

    .dsp_blocks_size = voice_ei_dsp_blocks_964091_1_size,
    .dsp_blocks = voice_ei_dsp_blocks_964091_1,

    .learning_blocks_size = voice_ei_learning_blocks_964091_1_size,
    .learning_blocks = voice_ei_learning_blocks_964091_1,

    .postprocessing_blocks_size = voice_ei_postprocessing_blocks_964091_1_size,
    .postprocessing_blocks = voice_ei_postprocessing_blocks_964091_1,

    .output_tensors_size = 1,

    .inferencing_engine = VOICE_EI_CLASSIFIER_TFLITE,

    .sensor = VOICE_EI_CLASSIFIER_SENSOR_MICROPHONE,
    .fusion_string = "audio",
    .slice_size = (16000/4),
    .slices_per_model_window = 4,

    .has_anomaly = VOICE_EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = voice_ei_classifier_inferencing_categories_964091_1,
    .results_type = VOICE_EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_964091_1_size,
    .freeform_outputs = freeform_outputs_964091_1
};

voice_ei_impulse_handle_t impulse_handle_964091_1 = voice_ei_impulse_handle_t( &impulse_964091_1 );

voice_ei_impulse_handle_t& voice_ei_default_impulse = impulse_handle_964091_1;
constexpr auto& voice_ei_classifier_inferencing_categories = voice_ei_classifier_inferencing_categories_964091_1;
const auto voice_ei_dsp_blocks_size = voice_ei_dsp_blocks_964091_1_size;
voice_ei_model_dsp_t *voice_ei_dsp_blocks = voice_ei_dsp_blocks_964091_1;
#endif // _VOICE_EI_CLASSIFIER_MODEL_VARIABLES_H_
